[build]
  command = "yarn run build"
  publish = "dist"
  NODE_ENV = "10.15.3"

[dev]
  command = "yarn run start"

[[redirects]]
  from = "/images/tiny/*"
  to = "/.netlify/images/?w=20&fit=cover&url=/images/:splat"
  status = 200

[[redirects]]
  from = "/images/mouse/*"
  to = "/.netlify/images/?w=150&fit=cover&url=/images/:splat"
  status = 200

[[redirects]]
  from = "/images/camping/*"
  to = "/.netlify/images/?w=200&fit=cover&url=/images/:splat"
  status = 200

[[redirects]]
  from = "/images/car/*"
  to = "/.netlify/images/?w=400&fit=cover&url=/images/:splat"
  status = 200

[[redirects]]
  from = "/images/bird/*"
  to = "/.netlify/images/?w=740&fit=cover&url=/images/:splat"
  status = 200

[[redirects]]
  from = "/images/mars/*"
  to = "/.netlify/images/?w=1024&fit=cover&url=/images/:splat"
  status = 200

[[redirects]]
  from = "/images/red/*"
  to = "/.netlify/images/?w=1200&fit=cover&url=/images/:splat"
  status = 200

[[redirects]]
  from = "/images/wow/*"
  to = "/.netlify/images/?w=1800&fit=cover&url=/images/:splat"
  status = 200

[[redirects]]
  from = "/images/original/*"
  to = "/.netlify/images/?url=/images/:splat"
  status = 200
